parser: babel-eslint

plugins:
  - flowtype
  - prettier

extends:
  - airbnb-base
  - prettier

env:
  node: true
  browser: false

rules:
  prettier/prettier:
    - error

  eqeqeq: [error, smart]
  no-undef: 0
  no-dupe-keys: error
  no-return-assign: 0
  consistent-return: 0

  no-use-before-define: 0
  no-param-reassign: 0
  class-methods-use-this: 0
  no-redeclare: 0

  import/prefer-default-export: 0
  import/no-extraneous-dependencies: 0

  flowtype/define-flow-type: error
  flowtype/no-mutable-array: error
  flowtype/no-types-missing-file-annotation: error
  flowtype/require-valid-file-annotation:
    [error, never, { annotationStyle: block }]
  flowtype/type-id-match: [error, '^[A-Z][a-z0-9]*']
  flowtype/use-flow-type: error
