language: node_js
node_js:
  - '10'

jobs:
  include:
    # - stage: Lint
    #   script: yarn lint
    # - stage: Flow check
    #   script: yarn flow
    - stage: Stable release
      if: tag =~ /^v[0-9]+\.[0-9]+\.[0-9]+$/
      deploy:
        provider: script
        skip_cleanup: true
        script:
          - yarn build
          - yarn semantic-release
