language: node_js
node_js:
  - '10'
  - '12'

jobs:
  include:
    - stage: Lint
      script: yarn lint
    - stage: Flow check
      script: yarn flow
    - stage: Test
      script: yarn test
    - stage: Release
      if: branch = master
      node_js: '12'
      script:
        - yarn build
        - npx semantic-release
