language: node_js
node_js:
  - '8'
  - '10'
  - 'node'

jobs:
  include:
    # - stage: Lint
    #   script: yarn lint
    # - stage: Flow check
    #   script: yarn flow
    - stage: Stable release
      node_js: node
      script:
        - yarn build
        - npx semantic-release
