language: node_js
node_js:
  - '10'

jobs:
  include:
    # - stage: Lint
    #   script: yarn lint
    # - stage: Flow check
    #   script: yarn flow
    - stage: release
      node_js: lts/*
      deploy:
        provider: script
        skip_cleanup: true
        script:
          - yarn semantic-release
